name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Compute version
        run: |
          TODAY=$(date +'%Y%m%d')
          COUNT=$(git rev-list --count --since="$(date +'%Y-%m-%d')T00:00:00" HEAD)
          echo "APP_VERSION=v.${TODAY}.$(printf '%03d' $COUNT)" >> $GITHUB_ENV
      - name: Deploy to Fly.io
        run: flyctl secrets set APP_VERSION=${{ env.APP_VERSION }} && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
